name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mc: [1.8.8]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.mc == '1.8.8' && 8 || 16 }}  
    
    - name: Make gradlew executable
      run: chmod +x ./gradlew  
      
    - name: Build test jar
      run: ./gradlew testJar
      
    - name: Install spigot ${{ matrix.mc }}
      run: |
          wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
          java -jar BuildTools.jar --rev ${{ matrix.mc }}
          mv spigot-${{ matrix.mc }}.jar spigot.jar
          
    - name: Copy to plugins directory
      run: |
        mkdir -p plugins
        cp build/libs/SupraHolograms-Test.jar plugins/
        
    - name: Start server and stop it
      run: |
        echo "eula=true" > eula.txt
        echo "level-type=FLAT" > server.properties
        java -Xmx2G -jar spigot.jar &
        sleep 120
        test
        sleep 10
        killall java

    - name: Check server logs, error if no match
      run: |
        if ! grep -q "Tests success" logs/latest.log; then
          echo "Server did not start correctly"
          exit 1
        fi
